"""Create original vector artwork from saved observed targets, without external assets."""
from pathlib import Path
from html import escape

def build_hero(payload, destination):
    series=[(s,payload['series'][f'{s}|Chronos-2|720|24']['rows']) for s in payload['stations']]
    first=min(r[0] for _,rows in series for r in rows)
    last=max(r[0] for _,rows in series for r in rows)
    peak=max(r[1] for _,rows in series for r in rows)
    parts=['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 560 370" role="img" aria-labelledby="title desc">',
        '<title id="title">Twelve observed station histories</title>',
        '<desc id="desc">Original layered PM2.5 traces from sampled observed test targets. A shared vertical scale and chronological horizontal axis are used. Artistic vertical offsets separate stations; this is not a map.</desc>',
        '<metadata>Source: Song Chen (2017), UCI Beijing Multi-Site Air Quality, doi:10.24432/C5RK5G. Derived artwork: StationShift, CC BY 4.0. Generated by scripts/build_hero.py.</metadata>']
    for j,(station,rows) in enumerate(series):
        baseline=170+j*16
        points=[(16+(r[0]-first)/(last-first)*528,baseline-r[1]/peak*125) for r in rows]
        line=' '.join(('M' if i==0 else 'L')+f'{x:.2f},{y:.2f}' for i,(x,y) in enumerate(points))
        shade=round(225-j*5)
        color=f'rgb({shade-12},{shade+3},{shade})'
        parts.append(f'<g><title>{escape(station)} · observed PM2.5</title><path d="{line} L{points[-1][0]:.2f},360 L{points[0][0]:.2f},360 Z" fill="{color}"/><path d="{line}" fill="none" stroke="#54756d" stroke-opacity=".28" stroke-width=".8"/></g>')
    parts.append('</svg>')
    destination=Path(destination); destination.parent.mkdir(parents=True,exist_ok=True)
    destination.write_text('\n'.join(parts)+'\n',encoding='utf-8')
